var annotated =
[
    [ "Afficheur", "classAfficheur.html", "classAfficheur" ],
    [ "AmeliorationCritique", "classAmeliorationCritique.html", "classAmeliorationCritique" ],
    [ "AmeliorationDegat", "classAmeliorationDegat.html", "classAmeliorationDegat" ],
    [ "AmeliorationPrecision", "classAmeliorationPrecision.html", "classAmeliorationPrecision" ],
    [ "Arme", "classArme.html", "classArme" ],
    [ "Attaquant", "classAttaquant.html", "classAttaquant" ],
    [ "Branche", "classBranche.html", "classBranche" ],
    [ "Classe", "classClasse.html", "classClasse" ],
    [ "ClasseDivine", "classClasseDivine.html", "classClasseDivine" ],
    [ "ClasseHeroique", "classClasseHeroique.html", "classClasseHeroique" ],
    [ "ClasseParangon", "classClasseParangon.html", "classClasseParangon" ],
    [ "CreateurPersonnage", "classCreateurPersonnage.html", "classCreateurPersonnage" ],
    [ "Decorator", "classDecorator.html", "classDecorator" ],
    [ "Defenseur", "classDefenseur.html", "classDefenseur" ],
    [ "Epee", "classEpee.html", "classEpee" ],
    [ "GenerateurPersonnage", "classGenerateurPersonnage.html", "classGenerateurPersonnage" ],
    [ "Instancieur", "classInstancieur.html", "classInstancieur" ],
    [ "Item", "classItem.html", "classItem" ],
    [ "Lance", "classLance.html", "classLance" ],
    [ "Marchand", "classMarchand.html", "classMarchand" ],
    [ "Personnage", "classPersonnage.html", "classPersonnage" ],
    [ "Posture", "classPosture.html", "classPosture" ],
    [ "Race", "classRace.html", "classRace" ],
    [ "Soigneur", "classSoigneur.html", "classSoigneur" ],
    [ "Sort", "classSort.html", "classSort" ],
    [ "Tacticien", "classTacticien.html", "classTacticien" ],
    [ "Technique", "classTechnique.html", "classTechnique" ],
    [ "TechniqueStatistique", "classTechniqueStatistique.html", "classTechniqueStatistique" ]
];